thompsonsj/slate-serializers

package-lock.json, package.json, src/index.spec.ts, src/index.ts, src/serializers/htmlToSlate/index.spec.ts, src/serializers/htmlToSlate/index.ts, src/serializers/slatetoHtml/index.spec.ts, src/serializers/slatetoHtml/index.ts, src/utilities/index.ts
Initial versions of the `htmlToSlate` and `slateToHtml` serializers.
=> feat(serializers): htmlToSlate and slateToHtml

src/__tests__/fixtures/textTags.ts, src/serializers/htmlToSlate/index.ts, src/serializers/slatetoHtml/index.ts
Improve text tag support and the logic used to construct text elements with any surrounding text tags.
=> feat(slatetohtml): improve text tag support

README.md, src/__tests__/combined.spec.ts, src/__tests__/fixtures/combined.ts, src/__tests__/fixtures/elementTags.ts, src/__tests__/fixtures/textTags.ts, src/index.ts, src/serializers/htmlToSlate/index.ts, src/serializers/slatetoHtml/index.spec.ts, src/serializers/slatetoHtml/index.ts
Documentation for this feature can be found in the changes to `README.md` included in this pull request, as well as the comments in `src/__tests__/fixtures/combined.ts`.
=> refactor(slatetohtml): add top-level p tags where appropriate

README.md
In response to https://github.com/thompsonsj/slate-serializers/issues/12.
=> docs(readme.md): add compatibility info

__tests__/serializers/htmlToSlate/index.spec.ts, __tests__/serializers/htmlToSlate/slateDemo.spec.ts, __tests__/serializers/slateToHtml/index.spec.ts, docs/engineering.md, package-lock.json, package.json, src/config/slatetoDom/default.ts, src/config/slatetoDom/types.ts, src/serializers/htmlToSlate/index.ts, src/serializers/slatetoHtml/index.ts
See docs added in docs/engineering.md.
=> feat(*to*): handle html entities appropriately

__tests__/serializers/htmlToSlate/index.spec.ts, src/config/htmlToSlate/default.ts, src/config/htmlToSlate/slateDemo.ts, src/config/htmlToSlate/types.ts
Reverts thompsonsj/slate-serializers#26
Easier to merge https://github.com/thompsonsj/slate-serializers/pull/24 and then redo this pull request.
=> Revert "refactor(config): extend all config from a sensible default"

__tests__/serializers/htmlToSlate/index.spec.ts, src/config/htmlToSlate/default.ts, src/config/htmlToSlate/slateDemo.ts, src/config/htmlToSlate/types.ts
Redo https://github.com/thompsonsj/slate-serializers/pull/26.
=> refactor(config): extend all config from a sensible default

package-lock.json, package.json
Update to resolve vulnerabilities as identified by `npm`.
`npm install` after this upgrade:
```
added 2 packages, removed 2 packages, changed 30 packages, and audited 731 packages in 15s
found 0 vulnerabilities
```
=> build(package.json): update dependencies

__tests__/serializers/slateToHtml/index.spec.ts, docs/engineering.md, src/config/slatetoDom/default.ts, src/config/slatetoDom/types.ts, src/serializers/blocks.ts, src/serializers/htmlToSlate/whitespace.ts, src/serializers/slatetoHtml/index.ts, src/utilities/domhandler.ts
Addresses https://github.com/thompsonsj/slate-serializers/issues/32
=> feat(slatetohtml): convert line breaks to br tags

__tests__/serializers/combined/sameHtmlSlateBothWays.spec.ts, __tests__/serializers/htmlToSlate/index.spec.ts, src/index.ts, src/serializers/htmlToSlate/index.ts
Work on https://github.com/thompsonsj/slate-serializers/issues/39.
=> wip(htmltoslate): investigate #39

package-lock.json, package.json
=> fix(package.json): move css-select dependency

packages/dom/src/lib/config/default.ts, packages/dom/src/lib/utilities/convert-slate.ts, packages/html/src/lib/serializers/slateToHtml/index.spec.ts, packages/utilities/src/lib/utilities.ts
Fix https://github.com/thompsonsj/slate-serializers/issues/105.
=> feat(default): encodeEntities default false

packages/html/src/lib/serializers/htmlToSlate/index.spec.ts
Test change in https://github.com/thompsonsj/slate-serializers/pull/114.
=> test(htmltoslate): add test for #114

package-lock.json, package.json, packages/react/src/lib/config/default.tsx, packages/react/src/lib/serializers.tsx
=> fix(react): patch non-maintained ulid dependency

packages/dom/package.json, packages/html/package.json, packages/react/package.json, packages/slate-serializers/package.json, packages/template/package.json, packages/tests/package.json, packages/utilities/package.json
Bump version consistent with https://github.com/thompsonsj/slate-serializers/pull/154.
=> chore(packages.json): version 2.2.1

packages/html/src/lib/tests/slateToHtml/configuration/elementMap.spec.ts
Example for https://github.com/thompsonsj/slate-serializers/issues/150.
=> test(elementmap): add table test

README.md
Point to package README.md files rather than the project root.
=> docs(readme): update root readme

packages/dom/src/lib/utilities/convert-slate.ts, packages/html/src/lib/serializers/slateToHtml/payload.spec.ts
Add fix and test for https://github.com/thompsonsj/slate-serializers/pull/141.
=> fix(convertslate): pass attribs to defaultTag

packages/html/src/lib/tests/htmlToSlate/configuration/htmlUpdaterMap.spec.ts
Add test to demonstrate https://github.com/thompsonsj/slate-serializers/issues/148.
=> test(htmlupdatermap): add test to demonstrate #148

packages/html/src/lib/tests/htmlToSlate/configuration/htmlUpdaterMap.spec.ts
Add simplified test based on https://github.com/thompsonsj/slate-serializers/pull/189 intended for the docs in https://github.com/thompsonsj/slate-serializers-demo.
=> test(htmlupdatermap): add simplified test based on #148
