thompsonsj/slate-serializers

package-lock.json, package.json, src/__tests__/fixtures/combined.ts, src/serializers/htmlToSlate/index.spec.ts, src/serializers/htmlToSlate/index.ts, src/utilities/index.ts
Original Slate JSON objects can contain line breaks in `text` fields. These line breaks are important for formatting. e.g. they may be used instead of a paragraph tag to form a new line. Make sure they are supported by both `htmlToSlate` and `slateToHtml`.
=> feat(htmltoslate): support line breaks

README.md, src/__tests__/combined.spec.ts, src/__tests__/fixtures/combined.ts, src/serializers/htmlToSlate/index.ts, src/serializers/slatetoHtml/index.ts, src/types.ts, src/utilities/index.ts
Support custom attribute mapping. Attributes in Slate can be mapped to HTML attributes and vice versa.
In the case of Payload CMS, this is a useful feature: we can preserve the `linkType` field which determines whether a link is `custom` (manually defined) or internal (links to a document in the CMS).
=> feat(*): support custom attributes

CHANGELOG.md, README.md, package-lock.json, package.json, src/__tests__/combined.spec.ts, src/index.ts, src/serializers/slatetoHtml/index.ts, src/utilities/domhandler.spec.ts, src/utilities/domhandler.ts
Convert Slate JSON to a DOM first, then serialize to a string using [`dom-serializer`](https://www.npmjs.com/package/dom-serializer).
Considering that `htmlparser2` and its associated utilities are being used for `htmlToSlate`, it makes sense that these powerful utilities are also used the other way round.
The Slate to HTML serializer is based on https://docs.slatejs.org/concepts/10-serializing#html, but it's time to move away from writing strings directly. The code becomes much easier to work with when building a DOM document from the Slate JSON, and then using [dom-serializer](https://www.npmjs.com/package/dom-serializer) to write out a string.
Rationale:
- **Cleaner logic**. Avoid writing utilities/functionality for writing HTML strings - e.g. `<p${prependSpace(attrs.join(' …
=> refactor(slatetohtml): convert to dom instead of html strings

__tests__/serializers/htmlToSlate/index.spec.ts, __tests__/serializers/slateToHtml/index.spec.ts, package-lock.json, package.json, src/serializers/slatetoHtml/index.ts
Fix double encoding of HTML special characters.
https://github.com/thompsonsj/slate-serializers/pull/9 introduced serializing to a DOM rather than trying to write our own HTML using strings.
Since this change, encoding rules for HTML entities/special characters is automatically handled by [`htmlparser2`](https://github.com/fb55/htmlparser2) and associated utilities, based on what type of node they are rendering (e.g. a text node or an element).
This removes the need for the [`html-escaper`](https://www.npmjs.com/package/html-escaper) dependency. Use of it, and the dependency itself is removed. This avoids issues that were arising such as:
`I'm` in a Slate JSON `text` property being rendered as `I&amp;m` in HTML.
=> fix(slatetohtml): do not escape encoded HTML special characters

__tests__/serializers/slateToHtml/index.spec.ts, src/config/slatetoDom/default.ts, src/serializers/slatetoHtml/index.ts
Add on option to control whether or not HTML entities are encoded.
`slateToHtml` encodes HTML entities by default. This the default behaviour of [`dom-serializer`](https://www.npmjs.com/package/dom-serializer).
It's a sensible default, and it is likely what we want when rendering HTML.
However, in some use cases, it makes sense to disable HTML entity encoding. For example, CrowdIn displays them as special characters when localizing a HTML document. When sending HTML to CrowdIn and reserializing content back to Slate JSON, it makes sense to disable entities for easier reading, editing and localization.
=> feat(slatetohtml): control html entity encoding

.gitignore, README.md, __tests__/serializers/combined/fixtures/combined.ts, __tests__/serializers/htmlToSlate/index.spec.ts, __tests__/serializers/htmlToSlate/whitespace.spec.ts, docs/development.md, docs/engineering.md, package-lock.json, src/config/htmlToSlate/default.ts, src/serializers/htmlToSlate/index.ts, src/serializers/htmlToSlate/whitespace.ts
Process whitespace depending on context.
- If within `code` or `pre` tags, don't do any processing.
- If within a [block formatting context](https://developer.mozilla.org/en-US/docs/Web/Guide/CSS/Block_formatting_context), normalize whitespace and remove space from the beginning and end of the block contents.
- If within an [inline formatting context](https://developer.mozilla.org/en-US/docs/Web/CSS/Inline_formatting_context), normalize whitespace.
This type of processing means that some Slate nodes can become empty. Additional filtering is added to clean up these empty nodes that do not add any meaning.
Docs added within the pull request.
=> feat(htmltoslate): process whitespace depending on context

__tests__/serializers/htmlToSlate/index.spec.ts, src/serializers/htmlToSlate/index.ts
> All Element nodes must contain at least one Text descendant — even [Void Elements](https://github.com/concepts/02-nodes#voids). If an element node does not contain any children, an empty text node will be added as its only child.
https://docs.slatejs.org/concepts/11-normalizing
=> fix(htmltoslate): ensure empty children have a text node

__tests__/serializers/htmlToSlate/index.spec.ts, __tests__/serializers/slateToHtml/index.spec.ts, docs/engineering.md, src/config/htmlToSlate/default.ts, src/config/htmlToSlate/types.ts, src/serializers/htmlToSlate/index.ts
When parsing the following examples, the serializer would break with the following errors
```sh
/node_modules/slate-serializers/lib/serializers/htmlToSlate/index.js:149
if (!('children' in element))
^
TypeError: Cannot use 'in' operator to search for 'children' in
at isSlateDeadEnd (/node_modules/slate-serializers/lib/serializers/htmlToSlate/index.js:145:22)
at /node_modules/slate-serializers/lib/serializers/htmlToSlate/index.js:34:31
at Array.map (<anonymous>)
...
```
This happens at `isSlateDeadEnd` and `addTextNodeToEmptyChildren` methods. The reason is that for self-closing tags like `<br>` and tags with empty contents like `<p></p>` the element these functions receive is an empty string instead of elements. The `in` operator works perfectly for objects, but not for empty strings
This …
=> fix: error when parsing empty or self-closing tags

__tests__/serializers/htmlToSlate/index.spec.ts
Ensure multiple `<br>` HTML elements are converted to line break characters in the resulting Slate object using the default configuration.
=> test(htmltoslate): br tag to line break tests

__tests__/serializers/htmlToSlate/index.spec.ts, src/config/htmlToSlate/default.ts, src/config/htmlToSlate/slateDemo.ts, src/config/htmlToSlate/types.ts
Extend both the `slateDemo` and `payload` config from a sensible default config.
=> refactor(config): extend all config from a sensible default

__tests__/serializers/combined/fixtures/elementTags.ts, __tests__/serializers/combined/sameHtmlSlateBothWays.spec.ts, __tests__/serializers/htmlToSlate/index.spec.ts, __tests__/serializers/slateToHtml/index.spec.ts, src/serializers/htmlToSlate/index.ts, src/serializers/htmlToSlate/whitespace.ts, src/serializers/slatetoHtml/index.ts
Several changes in this commit
- Added `isNextSiblingBlock` as a way to determine whether whitespace needs to be trimmed in the text before the next block element ([see updated fixture](https://github.com/thompsonsj/slate-serializers/pull/38/files#diff-b8c31d1cd177f2fdc6a6d4c856f9e1fe5501def07d3a5a2651f26eeb7a63252eR136) example)
- Added `htmlFromSlate` as an addition to `html` in unit tests, since the slate-to-html conversion is not necessarily leads to the same `html` (because of whitespace collapse)
- Fixed wrong `<br>` insertion after inline elements
- Prevent adding line break when within `<br>`  is happen to be within text nodes
=> fix(html-to-slate): trim whitespace that precedes a block element

README.md, docs/engineering.md, src/config/slateToDom/default.ts, src/config/slateToDom/payload.ts, src/config/slateToDom/slateDemo.ts, src/config/slateToDom/types.ts, src/serializers/slateToHtml/index.ts
Fixes https://github.com/thompsonsj/slate-serializers/issues/46.
Issue caused by working in a case insensitive environment. This has broken `slateToHtml` imports from version `0.0.27` installed as a node module. The path was changed in https://github.com/thompsonsj/slate-serializers/pull/40 to use the same capitalisation as the folder, but the folder name still had the incorrect capitalisation in the git repository.
See https://stackoverflow.com/questions/3011625/git-mv-and-only-change-case-of-directory
=> fix(src): folder capitalisation

package-lock.json, package.json
Fixes https://github.com/thompsonsj/slate-serializers/issues/44.
Downgrading `htmlparser2` to version 7 increases compatibility with Webpack 4. `htmlparser2` version 8 uses syntax added in Webpack 5. This issue is well explained in https://github.com/fb55/htmlparser2/issues/1237#issuecomment-1182522861.
Tests pass with this downgrade, so I see no reason not to do it. Can revisit at a later stage.
- https://github.com/cheeriojs/cheerio/issues/2545
- https://github.com/fb55/htmlparser2/issues/1237#issuecomment-1182522861
=> fix(package.json): downgrade htmlparser2 for Webpack 4 compatibility

__tests__/serializers/slateToDom/index.spec.ts
Fix failing test, possibly caused by https://github.com/thompsonsj/slate-serializers/pull/49.
Not a cause for concern as this is an edge case - it does not test the core behaviour of the package. Rather, it adjusts typing when using the `dom-serializer` package directly.
=> fix(slatetodom): parseDocument argument type

__tests__/serializers/htmlToSlate/index.spec.ts, src/serializers/htmlToSlate/index.ts
Changes:
- Added a unit test for `<p>Line 1<br>\n<span>Line 2</span></p>` conversion
- Renamed `parent` to `currentEl` within `deserialize` function since that name was confusing
- Added stripping of empty space before and after `<br>`
There'll probably be more changes if issues arise.
=> Improved <br> conversion

__tests__/serializers/slateToHtml/index.spec.ts, src/config/slateToDom/default.ts, src/config/slateToDom/types.ts, src/serializers/slateToHtml/index.ts, src/utilities/index.ts
Add an `alwaysEncodeBreakingEntities` option to `slateToDom`.
- Breaking entities are defined as `<`, `>` and `&` only.
- `alwaysEncodeBreakingEntities` only takes effect if `encodeEntities` is `false`. This is because `encodeEntities` encodes breaking entities anyway.
In CrowdIn, encoded entities are supported. Translators can hover over encoded entities to see the character used.
However, it would be much more convenient to send `utf8` characters as they are. This makes translations easier to manage, and avoids situations where translations receive a warning because an encoded entity is not included in the translation.
=> feat(slatetodom): add alwaysEncodeBreakingEntities option

package-lock.json, package.json
Upgrade all dependencies except `htmlparser2`.
`htmlparser2` is at version 9, but shouldn't be upgraded until we can confirm it works with Webpack 4. See https://github.com/thompsonsj/slate-serializers/pull/49.
=> build(package.json): upgrade dependencies

__tests__/serializers/slateToHtml/index.spec.ts, __tests__/utilities/domhandler.spec.ts, docs/config/slateToDom.md, package-lock.json, package.json, src/config/slateToDom/types.ts, src/serializers/slateToHtml/index.ts, src/utilities/domhandler.ts
Add a `markTransforms` config option to the `slateToDomConfig`.
Documentation and tests included in the pull request.
https://github.com/thompsonsj/slate-serializers/issues/59 describes an issue where inline styles are not included in the resulting HTML for `slateToHtml`.
Examining the issue, it seems that Slate is set up in such a way that it is adding additional properties to individual child nodes if a `p` type.
e.g.
```ts
[
{
type: 'p',
children: [
{
bold: true,
style: {
fontSize: '96px',
}
},
text: 'Paragraph',
},
],
}
]
```
This suggests that attributes are being set on HTML formatting elements. In this case, we should expect (assuming the appropriate configuration has been added to support a style object): `<p><strong style="font-size: 96px;">Paragraph</strong></p>`;
This is a job …
=> feat(slatetohtml): mark transforms

__tests__/serializers/slateToHtml/index.spec.ts, docs/config/slateToDom.md, src/serializers/slateToHtml/index.ts, src/utilities/index.ts
The `markTransforms` option was added to `SlateToDomConfig` in https://github.com/thompsonsj/slate-serializers/pull/63 in order to address https://github.com/thompsonsj/slate-serializers/issues/59.
On review, this option is confusing - and not very useful. It allows transform functions to be defined on HTML mark elements. e.g. anytime a `<strong>` HTML element tag is getting inserted, perform a transform function as defined.
It makes more sense to define mark transform functions on Slate JSON properties. For example, if a style object is set on a Slate child node, a transform function can be defined for that property. e.g. anytime a `style` property is found on a Slate node, return a `<span>` element with the style attributes added inline.
Functionality changed, tests added and docs …
=> refactor(slatetodom)!: apply markTransforms on Slate JSON properties

__tests__/serializers/slateToHtml/payload.spec.ts, src/config/slateToDom/payload.ts, src/config/slateToDom/types.ts, src/index.ts, src/utilities/convert-slate.ts
- Export an `ElementTagTransformFunction` type to make it easier to write element transform functions for  configs of type`SlateToDomConfig`.
- Add basic support for the upload field to the default Payload CMS config and add tests.
=> refactor(src): export a type for elementTransform fns

src/serializers/htmlToSlate/index.ts
Call to gatherTextMarkAttributes in src\serializers\htmlToSlate\index.ts was not being passed the config object and was thus using the default config. 
This prevented custom textTags and other settings being correctly utilised.
=> Fixed call to gatherTextMarkAttributes using default config

package.json, packages/dom/package.json, packages/html/package.json, packages/react/package.json, packages/slate-serializers/package.json, packages/template/package.json, packages/tests/package.json, packages/utilities/package.json
https://github.com/thompsonsj/slate-serializers/pull/109 is a breaking change - it changes the default config.
To restore to the original config, users needs to pass the original defaults.
```
slateToHtml(slate, {
...slateToHtmlConfig,
encodeEntities: true,
alwaysEncodeBreakingEntities: false,
})
```
=> chore(packages.json): bump to version 2.0.0

packages/slate-serializers/project.json
Without this change, `slate-serializers` requires `peerDepenendencies` to be installed.
=> fix(project.json): buildableProjectDepsInPackageJsonType

packages/react/package.json
Without this fix, the following error message can occur in projects that use `@slate-serializers/react` depending on the TypeScript configuration.
```bash
Type error: Could not find a declaration file for module '@slate-serializers/react'. '<project-dir>/node_modules/@slate-serializers/react/index.mjs' implicitly has an 'any' type.
There are types at '<project-dir>/node_modules/@slate-serializers/react/index.d.ts', but this result could not be resolved when respecting package.json "exports". The '@slate-serializers/react' library may need to update its package.json or typings.
```
=> fix(react): remove exports entry

package.json, packages/dom/package.json, packages/html/package.json, packages/react/package.json, packages/react/project.json, packages/slate-serializers/package.json, packages/template/package.json, packages/tests/package.json, packages/utilities/package.json, tools/sync-versions.js
Struggling to get `@slate-serializers/react` to bundle dependencies into the build `package.json`.
Resources:
- https://github.com/nrwl/nx/issues/10395
- https://stackoverflow.com/questions/71130822/building-an-nx-lib-with-rollup-does-not-bundle-required-dependencies
Fortunately, the package only relies on `@slate-serializers/dom`. Configure the version/deploy logic to ensure this package is always included as a dependency.
=> fix(react): workaround non-bundled dependency

package-lock.json, packages/dom/src/lib/config/default.ts, packages/html/src/lib/serializers/htmlToSlate/config/types.ts, packages/html/src/lib/serializers/snapshots/htmlToSlateToHtml.spec.ts
Ensure that both `slateToHtml` and `htmlToSlate` default configurations parse the `text-align` CSS attribute in the same way.
See:
- https://github.com/thompsonsj/slate-serializers/issues/118
- https://github.com/thompsonsj/slate-serializers/issues/59
...also lack of `align` attribute support has been mentioned a few times in the Payload CMS Discord. The `elementAttributeTransform` property on the `htmlToSlate` default config is imported by the Payload CMS config, so `text-align` on a style attribute will be transformed to the expected Slate JSON attribute for https://github.com/payloadcms/payload/tree/main/packages/richtext-slate.
Finally, an example is added through a test of how to use the `transformStyleObjectToString` and `transformStyleStringToObject` functions from …
=> fix(slatetohtml): parse align attribute, add style object example

tsconfig.base.json
Fix https://github.com/thompsonsj/slate-serializers/issues/146.
Disable source map generation in the npm package bundle.
Source maps offer developer convenience. I have experimented with different `tsconfig` options to try to try and resolve this issue while still supporting source maps, but to no avail. See https://github.com/nrwl/nx/issues/11179 for more information on the problem.
Seems more appropriate to disable source map generation and therefore remove warnings for source maps that were not working anyway.
=> fix(tsconfig): disable sourceMap

packages/dom/src/lib/config/payload.ts
When testing the html searlizer, I noticed that the text alignment wasn't being honored. Looking at the data that was created when using slate js with payload, it sets the textAlignment field. This PR checks both the align or textAlign field for the payload config
`[{"type": "h1", "children": [{"text": "Test body with image"}], "textAlign": "center"}, {"children": [{"text": ""}]}, {"type": "upload", "value": {"id": 4}, "children": [{"text": ""}], "textAlign": "center", "relationTo": "media"}, {"children": [{"text": ""}]}, {"children": [{"text": ""}]}, {"children": [{"text": "Some other text"}]}]`
=> patch(payload): adding textAlign key to be used

LICENSE.md
Add LICENSE.md as suggested in https://github.com/thompsonsj/slate-serializers/issues/178.
Following guidance at https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository, an MIT license is added - the [simple and permissive option](https://choosealicense.com/).
=> docs(license): add license

packages/dom/src/lib/config/payload.ts, packages/react/src/lib/__tests__/#175.spec.tsx, packages/react/src/lib/__tests__/default.spec.tsx, packages/react/src/lib/__tests__/payload-crowdin-sync-dev/payload-internal-link.spec.tsx, packages/react/src/lib/config/default.tsx, packages/react/src/lib/config/payload.tsx, packages/react/src/lib/config/types.ts, packages/react/src/lib/serializers.tsx, packages/tests/src/lib/react/components.spec.tsx, packages/tests/src/lib/react/style-object.spec.tsx
This is a breaking change for the `SlateToReact` serializer that removes the `react` and `dom` property names.
Update your usage of the serializer by removing these keys.
For example, before this change, custom configuration was quite messy as it was necessary to spread more values within the default configuration.
```ts
import { SlateToReact, slateToReactConfig as defaultReactConfig, SlateToReactConfig } from '@slate-serializers/react'
const config: SlateToReactConfig = {
...defaultReactConfig,
dom: {
...defaultReactConfig.dom,
defaultTag: 'p',
},
react: {
...defaultReactConfig.react,
elementTransforms: {
...defaultReactConfig.react.elementTransforms,
button: ({ node, children = [] }) => {
return <Button onClick={onClick}>{children}</Button>
},
},
},
};
```
After the change:
```ts
import …
```
=> feat(react): flatten config
